config/routes.rb
Reporter::Application.routes.draw do

  resources :sessions do
    collection do
      get 'login'
      get 'logout'
      post 'login_attempt'
    end
  end

  resources :reports  do
    member do # member requires an id (member of something), collection is for everything
      get 'execute'
      post 'custom_execute'
      get 'download'
    end
  end

  resources :custom_variables do
    collection do # member requires an id (member of something), collection is for everything
      get 'select'
    end
  end

  mount Resque::Server, :at => "/resque"

   root :to => "sessions#login"

end

app/models/report.rb
class Report < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :file_name
  validates_presence_of :stored_sql

  has_many :owners
  has_many :users, through: :owners
  has_and_belongs_to_many :groups
  has_many :file_names


 def self.for_user(user_id)
    if User.find(user_id).is_admin?
     self.all.order("reports.name")
             .joins("INNER JOIN sql_files ON reports.sql_file_id = sql_files.id")
             .where("sql_files.updated_at > NOW()::DATE")
    else
     self.joins("LEFT JOIN groups_reports ON groups_reports.report_id = reports.id")
         .joins("LEFT JOIN groups ON groups_reports.group_id = groups.id")
         .joins("LEFT JOIN owners ON owners.report_id = reports.id")
         .joins("LEFT JOIN users ON users.id = owners.user_id")
         .joins("INNER JOIN sql_files ON reports.sql_file_id = sql_files.id")
         .where("groups.id = ? OR users.id = ?", User.find(user_id).group.id, user_id)
         .where("sql_files.updated_at > NOW()::DATE")
         .order("groups.name ASC")
         .order("reports.name")
    end
  end

  def self.without_group_with_owner(user_id)
    reports = Report.for_user(user_id)
    reports.joins("LEFT JOIN groups_reports ON groups_reports.report_id = reports.id")
           .joins("LEFT JOIN owners ON owners.report_id = reports.id")
           .where("group_id is null")
           .where("user_id is not null")
  end

  def self.without_group_without_owner(user_id)
    reports = Report.for_user(user_id)
    reports.joins("LEFT JOIN groups_reports ON groups_reports.report_id = reports.id")
           .joins("LEFT JOIN owners ON owners.report_id = reports.id")
           .where("group_id is null")
           .where("user_id is null")
  end


  def stored_sql=(stored_sql)
    # Store the sql in a clean way.
    stored_sql = stored_sql.squish
    super stored_sql
  end




  def has_custom_variables
    !self.stored_sql.to_s.match(/{{([A-Za-z0-9_]+)}}/).nil?
  end

  def fetch_custom_variables
     cvs = self.stored_sql.to_s.gsub(/{{([A-Za-z0-9_]+)}}/).map do |custom_variable|
            custom_variable.delete "{}"
     end
    cvs
  end

  def fill_custom_variables(params)
    sql = self.stored_sql.to_s
    adjusted_sql = sql.to_s.gsub(/{{([A-Za-z0-9_]+)}}/) do |custom_variable|
       param_array = params[custom_variable.delete("{}").to_sym]
       quoted = param_array.map{ |i|  %Q('#{i}') }.join(',')
       "(#{quoted})"
    end
    adjusted_sql
  end

  def current_user_only?
    (self.fetch_custom_variables.include? "current_user") && (self.fetch_custom_variables.count == 1)
  end





  def self.possible_owners
    User.all.where.not(:group => 'OUT').order(:username).map do |user|
      [user.display_name, user.id]
    end
  end

  def selected_owners
    self.users.collect {|x| x.id}
  end


  def self.possible_groups
    Group.all.order(:name).map do |group|
      [group.name, group.id]
    end
  end


  def selected_groups
    self.groups.collect {|x| x.id}
  end



  def get_additional_owners
    report_groups = self.groups.all.map(&:name)
    extra_owners = Array.new
    self.users.each do |user|
      if user.group && (!report_groups.include? user.group.name)
        extra_owners << user.display_name
      end
    end
    return extra_owners
  end

  def last_file_for_user(user_id)
    file = self.file_names.where("user_id = ?", user_id).first
    if file.nil?
      file = self.file_names.new(:user_id => user_id, :report_id => self.id)
    end
    file
  end


  def self.test_reports
    user_id = User.where(:username => 'bart.ariens').first.id
    Report.all.each do |report|
     unless report.has_custom_variables
       Resque.enqueue(Downloader,report.id, user_id)
     end
    end
  end




  # A quick hack since I couldn't get: accept_nested_attributes_for to work
  # If someone knows how to do this better, please let me know.
  def users=(user_ids)
    self.users.delete_all # Not very pretty
    user_ids.each do |user_id|
      self.users << User.find(user_id) unless user_id.blank?
    end
  end

  def groups=(group_ids)
    self.groups.delete_all # Not very pretty
    group_ids.each do |group_id|
      self.groups << Group.find(group_id) unless group_id.blank?
    end
  end

end

class ReportGroup < ActiveRecord::Base
  belongs_to :group
  belongs_to :report
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user
  def create   # /reports POST
    @report = Report.new(report_params)
    if @report.valid?
      flash[:notice] = 'Report was successfully updated.'
      @report.save!
      redirect_to @report
    end
  end

  def index  # /reports INDEX
    @reports = Report.for_user(@current_user.id)
    @groups  = Group.all
    @reports_without_group_with_owner    = Report.without_group_with_owner(@current_user.id)
    @reports_without_group_without_owner = Report.without_group_without_owner(@current_user.id)
  end

  def edit
    @report = Report.for_user(@current_user.id).find(params[:id])
  end

  def update
    @report = Report.for_user(@current_user.id).find(params[:id])
    if @report.update(report_params)
      flash[:notice] = 'Profile was successfully updated.'
      redirect_to(@report)
    else
      render "edit"
    end
  end

  def show # /reports/:id # GET
    @report = Report.for_user(@current_user.id).find(params[:id])
  end

  def execute # custom get
    @report = Report.for_user(@current_user.id).find(params[:id])
    if @report
      if @report.has_custom_variables && !@report.current_user_only?
        return redirect_to select_custom_variables_path(:report_id => @report)
      else
        custom_sql = @report.fill_custom_variables(params.merge(:current_user => [@current_user.id.to_s]))
        Resque.enqueue(Downloader, @report.id, @current_user.id, custom_sql)
        flash[:notice] = "Report is being executed please wait and press F5 to see if the report is finished"
      end
    else
      flash[:error] = "You're not allowed to execute this report."
    end

    redirect_to action: "index"
  end

  def destroy
    # does not actually delete the report, but clears the owners + groups
    report = Report.for_user(@current_user.id).find(params[:id])
    report.groups.delete_all
    report.owners.delete_all
    report.save!
    redirect_to action: "index"
  end

  def custom_execute # custom post, this is called after the custom selection form.
    @report = Report.for_user(@current_user.id).find(params[:id])
    custom_sql = @report.fill_custom_variables(params.merge(:current_user => [@current_user.id.to_s]))
    Resque.enqueue(Downloader, @report.id, @current_user.id, custom_sql)
    flash[:notice] = "Report with custom variables is being executed please wait and press F5 to see if the report is finished"
    redirect_to action: "index"
  end


  def download
    report = Report.for_user(@current_user.id).find(params[:id])
    if report && report.last_file_for_user(@current_user.id)
     file = report.last_file_for_user(@current_user.id).path_to_file
      send_file(file)
    else
      flash[:error] = "You're not allowed to delete this report."
    end
  end

  private
  def report_params
    params.require(:report).permit(:name, :stored_sql, :file_name, :users => [], :groups => [])
  end
end

app/views/reports/index/_for_admin.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% @groups.each do |group| %>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="heading_<%="#{group.name}"%>">
        <h4 class="panel-title">
          <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse_<%="#{group.name}"%>" aria-expanded="false" aria-controls="collapse_<%="#{group.name}"%>">
            Group: <%= "#{group.name} (#{@reports.joins(:groups).where("groups_reports.group_id = ?", group.id).count})" %>
          </a>
        </h4>
      </div>
      <div id="collapse_<%="#{group.name}"%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_<%="#{group.name}"%>">
        <div class="panel-body">
          <table border="1" cellpadding="5" width="100%">
            <%= render "reports/index/table_head" %>
              <% if @reports.first %>
                <% @reports.joins(:groups).where("groups_reports.group_id = ?", group.id).each do |report| %>
                <%= render "reports/index/item", :report => report %>
              <% end %>
           <% end %>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>



<% if @reports_without_group_with_owner %>
    <div class="panel-group" id="accordion2" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="heading_no_group_with_owner">
            <h4 class="panel-title">
              <a class="collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapse_no_group_with_owner" aria-expanded="false" aria-controls="collapse_no_group_with_owner">
                Reports without group(s) bit with owner(s) (<%= @reports_without_group_with_owner.count %>)
              </a>
            </h4>
          </div>
          <div id="collapse_no_group_with_owner" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_no_group_with_owner">
            <div class="panel-body">
              <table border="1" cellpadding="5" width="100%">
                <%= render "reports/index/table_head" %>
                <% @reports_without_group_with_owner.each do |report| %>
                    <%= render "reports/index/item", :report => report %>
                <% end %>
              </table>
            </div>
          </div>
        </div>
    </div>
<% end %>


<% if @reports_without_group_without_owner %>
    <div class="panel-group" id="accordion3" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading_no_group_without_owner">
          <h4 class="panel-title">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion3" href="#collapse_no_group_without_owner" aria-expanded="false" aria-controls="collapse_no_group_with_owner">
             Unassigned reports (<%= @reports_without_group_without_owner.count %>)
            </a>
          </h4>
        </div>
        <div id="collapse_no_group_without_owner" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_no_group_without_owner">
          <div class="panel-body">
            <table border="1" cellpadding="5" width="100%">
              <%= render "reports/index/table_head" %>
              <% @reports_without_group_without_owner.each do |report| %>
                  <%= render "reports/index/item", :report => report %>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
<% end %>

<br><br>

app/views/reports/index/_for_regular.html.erb
<% if @reports.count > 0 %>
    <table border="1" cellpadding="5">
          <%= render "reports/index/table_head" %>
      <% @reports.each do |report| %>
          <%= render "reports/index/item", :report => report %>
      <% end %>
<% else %>
    <p> No queries to download</p>
<% end %>
    </table>
    <br><br>

app/views/reports/index/_item.html.erb
<tr>
  <td><%= report.name %></td>
  <td><%= report.groups.all.map(&:name).join(", ")%></td>
  <td><%= report.get_additional_owners.join(", ") %> </td>
  <td><%= report.last_file_for_user(@current_user.id).updated_at %></td>
  <td><%= report.execution_time.round(2) if report.execution_time %></td>
  <% if report.last_file_for_user(@current_user.id).updated_at %>
      <td><%= link_to 'Download', download_report_path(report), :method => :get %></td>
  <% else %>
      <td>Execute first</td>
  <% end %>
  <td><%= link_to 'Execute', execute_report_path(report), :method => :get %></td>
  <% if is_admin? %>
      <td><%= link_to 'Edit', edit_report_path(report), :method => :get %></td>
      <td><%= link_to 'Clear Owners', report, data: { confirm: 'Are you sure?' }, :method => :delete %></td>
  <% end %>
</tr>

app/views/reports/index/_table_head.html.erb
<tr>
  <th>Title</th>
  <th>Groups</th>
  <th>Additional Owners</th>
  <th>Last Execution</th>
  <th>Execution Time (seconds)</th>
  <th>Download</th>
  <th>Execute</th>
  <% if is_admin? %>
      <th>Edit</th>
      <th>Clear Owners</th>
  <% end %>
</tr>