config/routes.rb
Reporter::Application.routes.draw do

  resources :sessions do
    collection do
      get 'login'
      get 'logout'
      post 'login_attempt'
    end
  end

  resources :reports  do
    member do # member requires an id (member of something), collection is for everything
      get 'execute'
      post 'custom_execute'
      get 'download'
    end
  end

  resources :custom_variables do
    collection do # member requires an id (member of something), collection is for everything
      get 'select'
    end
  end

  mount Resque::Server, :at => "/resque"

   root :to => "sessions#login"

end

app/models/custom_variable.rb
class CustomVariable < ActiveRecord::Base
  #def self.fetch(custom_variable, user_id = nil)
  #
  #  if custom_variable == "current_user" && !user_id.nil?
  #    return user_id
  #  end
  #  custom_variable = custom_variable.delete "{}"
  #
  #  cv = CustomVariable.find_by_name(custom_variable) || raise("Somehow custom_variable's not set #{custom_variable}")
  #  results = External.connection.execute(cv.stored_sql)
  #  results
  #end


  def result
    results = External.connection.execute(self.stored_sql)
    array_result = results.map do |row|
                    [row['name'], row['value']]
    end
    array_result
  end
end

app/controllers/custom_variables_controller.rb
class CustomVariablesController < ApplicationController
  before_filter :authenticate_user
  def create   # /reports POST
    @cv = CustomVariable.new(cv_params)
    if @cv.valid?
      @cv.save
      flash[:notice] = 'Custom Variable was successfully updated.'
      redirect_to @cv
    end
  end

  def index  # /reports INDEX
    @cvs = CustomVariable.all
  end

  def show  # /reports/:id   # GET
    @cv = CustomVariable.find(params[:id])
  end

  def edit # PUT & PATCH
    @cv = CustomVariable.find(params[:id])
  end

  def update
    @cv = CustomVariable.find(params[:id])
    if @cv.update(cv_params)
      flash[:notice] = 'Profile was successfully updated.'
      redirect_to(@cv)
    else
      render "edit"
    end
  end

  def new # GET
    @cv = CustomVariable.new
  end

  def destroy  # DELETE
    @cv = CustomVariable.find(params[:id])
    if @current_user.is_admin?
      @cv.destroy
    else
      flash[:error] = "You're not allowed to delete this report."
    end

    redirect_to action: "index"
  end

  def select # custom get
    @report = Report.find(params[:report_id]) || raise("No report found")
    @cvs = @report.fetch_custom_variables
  end


  private
  def cv_params
    params.require(:custom_variable).permit(:name, :stored_sql)
  end
end

app/views/custom_variables/create.html.erb
<% if @cv.errors.any? %>
    <ul>
      <% @cv.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

app/views/custom_variables/edit.html.erb
<%= form_for @cv, url: custom_variable_path(@cv) do |f| %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :stored_sql %><br>
      <%= f.text_area :stored_sql %>
    </p>

    <p>
      <%= f.submit %>
    </p>


<% end %>

app/views/custom_variables/index.html.erb
<h1>Custom Variables Overview (Advanced Users only)</h1>


 <% if @cvs.count > 0 %>
    <table border="1" cellpadding="5">
      <tr>
        <th>Title</th>
        <th>Result</th>
        <% if is_admin? %>
        <th>Edit</th>
        <th>Destroy</th>
        <% end %>
      </tr>

      <tr>
        <td>current_user</td>
        <td><%= @current_user.id %></td>
        <td></td>
        <td></td>
      </tr>

      <% @cvs.each do |cv| %>
          <tr>
            <td><%= cv.name %></td>
            <td><%= cv.result.first ? cv.result.first : "Query not working"  %></td>
            <% if is_admin? %>
            <td><%= link_to 'Edit', edit_custom_variable_path(cv), :method => :get %></td>
            <td><%= link_to 'Destroy', cv, data: { confirm: 'Are you sure?' }, :method => :DELETE %></td>
            <% end %>
          </tr>
      <% end %>
   <% else %>
  <p> No custom variables set</p>
  <% end %>
</table>
<br><br>

<% if is_admin? %>
<%= link_to('new custom variable', :action => 'new') %>
<% end %>

app/views/custom_variables/new.html.erb
<%= form_for @cv, url: custom_variables_path do |f| %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :stored_sql %><br>
      <%= f.text_area :stored_sql %>
    </p>

    <p>
      <%= f.submit %>
    </p>


<% end %>

app/views/custom_variables/select.html.erb
<%= form_tag custom_execute_report_path(@report), :method=>'post'  do |f| %>
    <% error = false %>
    <% @cvs.each do |cv|%>
      <%= cv %>
      <% possible_selections =  CustomVariable.find_by_name(cv) %>
      <% if possible_selections %>
      <p><%= select_tag cv, options_for_select(possible_selections.result), :multiple => true, :style => "height: 400px"  %></p>
      <% elsif cv == 'current_user'  %>
            variable used. <br><br>
      <% else %>
      <% error = true %>
      Error: Custom Variable not set
      <% end %>
    <% end %>
<p><%= submit_tag 'Submit' if !error %></p>
<% end %>

app/views/custom_variables/show.html.erb
<%= @cv.name %>   <br>
<%= link_to('all custom variables', :action => 'index') %>