config/routes.rb
Reporter::Application.routes.draw do

  resources :sessions do
    collection do
      get 'login'
      get 'logout'
      post 'login_attempt'
    end
  end

  resources :reports  do
    member do # member requires an id (member of something), collection is for everything
      get 'execute'
      post 'custom_execute'
      get 'download'
    end
  end

  resources :custom_variables do
    collection do # member requires an id (member of something), collection is for everything
      get 'select'
    end
  end

  mount Resque::Server, :at => "/resque"

   root :to => "sessions#login"

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="#"></a>
</div>
<div class="navbar-collapse collapse">
  <ul class="nav navbar-nav">
    <% if user_signed_in? %>
    <li> <%= link_to('Reports', reports_url, :action => 'get') %></li>
    <% end %>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=user_signed_in? ? @current_user.username : "user" %> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <% if user_signed_in? %>
        <li><%= link_to('Logout', logout_sessions_url, :action=>'get') %></li>
        <% else %>
        <li> <%= link_to('Login', login_sessions_url, :action => 'get')  %> </li>
        <% end %>
      </ul>
    </li>
  </ul>
</div><!--/.nav-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "The Awesome Reporter Tool" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "The Awesome Reporter Tool" %>">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <%= render 'layouts/navigation' %>
  </div>
</div>

<div class="container">
  <%= render 'layouts/messages' %>
</div>
<div class="container">
    <%= yield %>
</div> <!-- /container -->

</body>
</html>